/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Frame;
import javax.swing.JTextField;

import javax.swing.WindowConstants;
import model.Konyv;

/**
 *
 * @author Gyöpös Marcell
 */
public class AddEditWindow extends javax.swing.JDialog {
    private Konyv konyv;
    
  //  private final JLabel szerzo = new JLabel("Szerző:");
 //   private final JLabel cim = new JLabel("Cím:");
//    private final JLabel kiado = new JLabel("Kiadó:");
   //private final JTextField szerzo_field = new JTextField();
    //private final JTextField cim_field = new JTextField();
    //private final JTextField kiado_field = new JTextField();
 //   private final JButton saveButt = new JButton("Save");
   // private final JButton Cancel = new JButton("Cancel");
    
    
    public AddEditWindow(Frame owner, String title, Konyv  konyv) {
        super(owner,title,true);
       
        this.konyv = konyv;
        this.szerzo_field.setText(konyv.getSzerzo());
        this.cim_field.setText(konyv.getCim());
        this.kiado_field.setText(konyv.getKiado());
        this.initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        szerzo = new javax.swing.JLabel();
        cim = new javax.swing.JLabel();
        kiado = new javax.swing.JLabel();
        Cancel = new javax.swing.JButton();
        saveButt = new javax.swing.JButton();
        szerzo_field = new javax.swing.JTextField();
        cim_field = new javax.swing.JTextField();
        kiado_field = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        szerzo.setText("Szerző:");

        cim.setText("Cim:");

        kiado.setText("Kiado");

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        saveButt.setText("Save");
        saveButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtActionPerformed(evt);
            }
        });

        szerzo_field.setText(" ");
        szerzo_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                szerzo_fieldActionPerformed(evt);
            }
        });

        cim_field.setText(" ");

        kiado_field.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cancel)
                        .addGap(99, 99, 99)
                        .addComponent(saveButt))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(kiado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(kiado_field))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(cim)
                            .addGap(18, 18, 18)
                            .addComponent(cim_field))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(szerzo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(szerzo_field, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(szerzo)
                    .addComponent(szerzo_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cim)
                    .addComponent(cim_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kiado)
                    .addComponent(kiado_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel)
                    .addComponent(saveButt))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtActionPerformed
        AddEditWindow.this.konyv.setSzerzo(AddEditWindow.this.szerzo_field.getText());
                AddEditWindow.this.konyv.setCim(AddEditWindow.this.cim_field.getText());
                AddEditWindow.this.konyv.setKiado(AddEditWindow.this.kiado_field.getText());
                AddEditWindow.this.dispose();
    }//GEN-LAST:event_saveButtActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        AddEditWindow.this.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void szerzo_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_szerzo_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_szerzo_fieldActionPerformed

    /**
     
     */
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form *
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEditWindow().setVisible(false);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel cim;
    private javax.swing.JTextField cim_field;
    private javax.swing.JLabel kiado;
    private javax.swing.JTextField kiado_field;
    private javax.swing.JButton saveButt;
    private javax.swing.JLabel szerzo;
    private javax.swing.JTextField szerzo_field;
    // End of variables declaration//GEN-END:variables

  


}
